export const essayThemesHTML = {
    "1": "These are three short <b>self-introductions</b> created by AITwinbot. ",
    "2": "These are four short essays about <b>your strengths and weaknesses</b> generated by AITwinBot.",
    "3": "These are four different descriptions about <b>yourself and your life ten years from now</b> generated by AITwinBot.",
    "4": "These are four short essays about <b>stress causes and reliefs</b> created by AITwinBot.",
    "5": "These are four short essays <b>defining happiness</b> created by AITwinBot."
} as { [key: string]: string };