'use client';

import { useRouter, useSearchParams } from "next/navigation";
import Text from "@/app/components/v1/Text";
import Button from "@/app/components/v1/Button";

// Add the import statement for JSX.IntrinsicElements
import React from "react";
import { defaultCondition, getPID } from "@/lib/v1/urlParams";

export default function Page() {
    const router = useRouter();
    const query = useSearchParams();

    const onClickYes = () => {
        let pID = getPID(query);
        router.push(`/v1/B/instruction?pID=${pID}`);
    };

    const onClickNo = () => {
        //이거 페이지로 따로 만들어야 할듯 / 일단 alert로 대체
        alert("Thank you for your time. We respect your decision not to participate. If you wish to join us in the future or have any inquiries, please don't hesitate to reach out to us.");
    };

    return (
        <div className="flex flex-col p-4">
            <p className="mb-7">
                The purpose of this study is to explore the potential of generative AI techniques, such as ChatGPT, by developing <b>AITwinBots</b>, which are digital avatars of you that reflect your personal characteristics, values, and identities.
            </p>
            <p>
                The study will last approximately 30-40 minutes and includes:
            </p>
            <div className="bg-gray-100 p-8 my-4">
                <div className="px-4">
                    <ol className="list-decimal">
                        <li className="mb-2">
                            <Text content="A survey to collect your demographics, life values, and lifestyle to create your AITwinBot(10-15 mins)." />
                        </li>
                        <li className="mb-2">
                            <Text content="An assessment of essays generated by your AITwinBot (20-25 mins)." />
                        </li>
                    </ol>
                </div>
            </div>

            <p>
                [!] Please participate in a <b><u>quiet setting</u></b> to ensure thoughtful responses, enhancing the accuracy of your AITwinBot.
            </p>
            <p>
                [!] Please use a <b><u>computer</u></b> for the survey.
            </p>
            <p>
                [!] In this survey, we&rsquo;ve included a number of questions designed to <b>check if you&rsquo;re paying attention</b>. It&rsquo;s important to answer these questions carefully because your responses help ensure the quality of our study.
            </p>
            <p>
                [!] If you <u>don&rsquo;t pass these attention checks multiple times</u>, or if the time you spend on the survey is much <u>shorter or longer than we expect</u>, you might not be eligible for compensation. Please take your time and answer each question thoughtfully
            </p>

            <p className="mt-7">
                Have you fully understood the information provided? Press “YES” to proceed to the next step.
            </p>
            <div className="flex justify-center items-center my-4 flex-col md:flex-row">
                <div className="m-2">
                    <Button label="YES" onClick={onClickYes} active={true} />
                </div>
                <div className="m-2">
                    <Button label="NO" onClick={onClickNo} active={true} />
                </div>
            </div>
        </div>
    );
}