export const questions_BFI = {
    'BFI-1': 'Tends to be quiet.',
    'BFI-2': 'Is compassionate, has a soft heart.',
    'BFI-3': 'Tends to be disorganized.',
    'BFI-4': 'Worries a lot.',
    'BFI-5': 'Is fascinated by art, music, or literature.',
    'BFI-6': 'Is dominant, acts as a leader.',
    'BFI-7': 'Is sometimes rude to others.',
    'BFI-8': 'Has difficulty getting started on tasks.',
    'BFI-9': 'Tends to feel depressed, blue.',
    'BFI-10': 'Has little interest in abstract ideas.',
    'BFI-11': 'Is full of energy.',
    'BFI-12': 'Assumes the best about people.',
    'BFI-13': 'Is reliable, can always be counted on.',
    'BFI-14': 'Is emotionally stable, not easily upset.',
    'BFI-15': 'Is original, comes up with new ideas.',
    'BFI-16': 'Is outgoing, sociable.',
    'BFI-17': 'Can be cold and uncaring.',
    'BFI-18': 'Keeps things neat and tidy.',
    'BFI-19': 'Is relaxed, handles stress well.',
    'BFI-20': 'Has few artistic interests.',
    'BFI-21': 'Prefers to have others take charge.',
    'BFI-22': 'Is respectful, treats others with respect.',
    'BFI-23': 'Is persistent, works until the task is finished.',
    'BFI-24': 'Feels secure, comfortable with self.',
    'BFI-25': 'Is complex, a deep thinker.',
    'BFI-26': 'Is less active than other people.',
    'BFI-27': 'Tends to find fault with others.',
    'BFI-28': 'Can be somewhat careless.',
    'BFI-29': 'Is temperamental, gets emotional easily.',
    'BFI-30': 'Has little creativity.',
}

export const bfiKeys = [
    'BFI-1',
    'BFI-2',
    'BFI-3',
    'BFI-4',
    'BFI-5',
    'BFI-6',
    'BFI-7',
    'BFI-8',
    'BFI-9',
    'BFI-10',
    'BFI-11',
    'BFI-12',
    'BFI-13',
    'BFI-14',
    'BFI-15',
    'BFI-16',
    'BFI-17',
    'BFI-18',
    'BFI-19',
    'BFI-20',
    'BFI-21',
    'BFI-22',
    'BFI-23',
    'BFI-24',
    'BFI-25',
    'BFI-26',
    'BFI-27',
    'BFI-28',
    'BFI-29',
    'BFI-30',
]

export const bfiReverse = {
    'BFI-1': true,
    'BFI-2': false,
    'BFI-3': true,
    'BFI-4': true,
    'BFI-5': false,
    'BFI-6': false,
    'BFI-7': true,
    'BFI-8': true,
    'BFI-9': false,
    'BFI-10': true,
    'BFI-11': false,
    'BFI-12': false,
    'BFI-13': false,
    'BFI-14': true,
    'BFI-15': false,
    'BFI-16': false,
    'BFI-17': true,
    'BFI-18': false,
    'BFI-19': true,
    'BFI-20': true,
    'BFI-21': true,
    'BFI-22': false,
    'BFI-23': false,
    'BFI-24': true,
    'BFI-25': false,
    'BFI-26': true,
    'BFI-27': true,
    'BFI-28': true,
    'BFI-29': true,
    'BFI-30': true,
} as { [key: string]: boolean }

export const bfiDomainsAndFacets = {
    'Extraversion': ['Sociability', 'Assertiveness', 'Energy Level'],
    'Agreeableness': ['Compassion', 'Respectfulness', 'Trust'],
    'Conscientiousness': ['Organization', 'Productiveness', 'Responsibility'],
    'Negative Emotionality': ['Anxiety', 'Depression', 'Emotional Volatility'],
    'Open-Mindedness': ['Aesthetic Sensitivity', 'Intellectual Curiosity', 'Creativite Imagination'],
}
export const bfiDomains = {
    'BFI-1': 'Extraversion',
    'BFI-2': 'Agreeableness',
    'BFI-3': 'Conscientiousness',
    'BFI-4': 'Negative Emotionality',
    'BFI-5': 'Open-Mindedness',
    'BFI-6': 'Extraversion',
    'BFI-7': 'Agreeableness',
    'BFI-8': 'Conscientiousness',
    'BFI-9': 'Negative Emotionality',
    'BFI-10': 'Open-Mindedness',
    'BFI-11': 'Extraversion',
    'BFI-12': 'Agreeableness',
    'BFI-13': 'Conscientiousness',
    'BFI-14': 'Negative Emotionality',
    'BFI-15': 'Open-Mindedness',
    'BFI-16': 'Extraversion',
    'BFI-17': 'Agreeableness',
    'BFI-18': 'Conscientiousness',
    'BFI-19': 'Negative Emotionality',
    'BFI-20': 'Open-Mindedness',
    'BFI-21': 'Extraversion',
    'BFI-22': 'Agreeableness',
    'BFI-23': 'Conscientiousness',
    'BFI-24': 'Negative Emotionality',
    'BFI-25': 'Open-Mindedness',
    'BFI-26': 'Extraversion',
    'BFI-27': 'Agreeableness',
    'BFI-28': 'Conscientiousness',
    'BFI-29': 'Negative Emotionality',
    'BFI-30': 'Open-Mindedness',
} as { [key: string]: string }

export const bfiFacets = {
    'BFI-1': 'Sociability',
    'BFI-2': 'Compassion',
    'BFI-3': 'Organization',
    'BFI-4': 'Anxiety',
    'BFI-5': 'Aesthetic Sensitivity',
    'BFI-6': 'Assertiveness',
    'BFI-7': 'Respectfulness',
    'BFI-8': 'Productiveness',
    'BFI-9': 'Depression',
    'BFI-10': 'Intellectual Curiosity',
    'BFI-11': 'Energy Level',
    'BFI-12': 'Trust',
    'BFI-13': 'Responsibility',
    'BFI-14': 'Emotional Volatility',
    'BFI-15': 'Creativite Imagination',
    'BFI-16': 'Sociability',
    'BFI-17': 'Compassion',
    'BFI-18': 'Organization',
    'BFI-19': 'Anxiety',
    'BFI-20': 'Aesthetic Sensitivity',
    'BFI-21': 'Assertiveness',
    'BFI-22': 'Respectfulness',
    'BFI-23': 'Productiveness',
    'BFI-24': 'Depression',
    'BFI-25': 'Intellectual Curiosity',
    'BFI-26': 'Energy Level',
    'BFI-27': 'Trust',
    'BFI-28': 'Responsibility',
    'BFI-29': 'Emotional Volatility',
    'BFI-30': 'Creativite Imagination',
} as { [key: string]: string }

