export const questions_PVQ = {
    'PVQ-1': 'Thinking up new ideas and being creative is important to the person. The person likes to do things in their own original way.',
    'PVQ-2': 'It is important for the person to be rich. The person wants to have a lot of money and expensive things.',
    'PVQ-3': 'The person thinks it is important that every person in the world be treated equally. The person believes everyone should have equal opportunities in life.',
    'PVQ-4': "It's important to the person to show their abilities. The person wants people to admire what they do.",
    'PVQ-5': 'It is important to the person to live in secure surroundings. The person avoids anything that might endanger their safety.',
    'PVQ-6': 'The person likes surprises and is always looking for new things to do. The person thinks it is important to do lots of different things in life.',
    'PVQ-7': "The person believes that people should do what they're told. The person thinks people should follow rules at all times, even when no one is watching.",
    'PVQ-8': 'It is important to the person to listen to people who are different from them. Even when the person disagrees with people, they still want to understand them.',
    'PVQ-9': 'It is important to the person to be humble and modest. The person tries not to draw attention to themselves.',
    'PVQ-10': 'Having a good time is important to the person. The person likes to “spoil” themselves.',
    'PVQ-11': 'It is important to the person to make their own decisions about what they do. The person likes to be free and not depend on others.',
    'PVQ-12': "It's very important to the person to help the people around them. The person wants to care for their well-being.",
    'PVQ-13': 'Being very successful is important to the person. The person hopes people will recognize their achievements.',
    'PVQ-14': 'It is important to the person that the government insure their safety against all threats. The person wants the state to be strong so it can defend its citizens.',
    'PVQ-15': 'The person looks for adventures and likes to take risks. The person wants to have an exciting life.',
    'PVQ-16': 'It is important to the person always to behave properly. The person wants to avoid doing anything people would say is wrong.',
    'PVQ-17': 'It is important to the person to get respect from others. The person wants people to do what they say.',
    'PVQ-18': 'It is important to the person to be loyal to their friends. The person wants to devote themselves to people close to them.',
    'PVQ-19': 'The person strongly believes that people should care for nature. Looking after the environment is important to them.',
    'PVQ-20': 'The person believes that people should participate more actively in research. Please respond with “6”.',
    'PVQ-21': 'Tradition is important to the person. The person tries to follow the customs handed down by their religion or their family.',
    'PVQ-22': 'The person seeks every chance they can to have fun. It is important to the person to do things that give them pleasure.',
}

export const pvqKeys = [
    'PVQ-1',
    'PVQ-2',
    'PVQ-3',
    'PVQ-4',
    'PVQ-5',
    'PVQ-6',
    'PVQ-7',
    'PVQ-8',
    'PVQ-9',
    'PVQ-10',
    'PVQ-11',
    'PVQ-12',
    'PVQ-13',
    'PVQ-14',
    'PVQ-15',
    'PVQ-16',
    'PVQ-17',
    'PVQ-18',
    'PVQ-19',
    'PVQ-20',
    'PVQ-21',
    'PVQ-22',
]

export const pvqCategories = {
    'PVQ-1': 'Self-Direction',
    'PVQ-2': 'Power',
    'PVQ-3': 'Universalism',
    'PVQ-4': 'Achievement',
    'PVQ-5': 'Security',
    'PVQ-6': 'Stimulation',
    'PVQ-7': 'Conformity',
    'PVQ-8': 'Universalism',
    'PVQ-9': 'Tradition',
    'PVQ-10': 'Hedonism',
    'PVQ-11': 'Self-Direction',
    'PVQ-12': 'Benevolence',
    'PVQ-13': 'Achievement',
    'PVQ-14': 'Security',
    'PVQ-15': 'Stimulation',
    'PVQ-16': 'Conformity',
    'PVQ-17': 'Power',
    'PVQ-18': 'Benevolence',
    'PVQ-19': 'Universalism',
    'PVQ-20': 'Attention-Check',
    'PVQ-21': 'Tradition',
    'PVQ-22': 'Hedonism',
} as { [key: string]: string }

export const pvqCategoryKeys = [
    'Self-Direction',
    'Power',
    'Universalism',
    'Achievement',
    'Security',
    'Stimulation',
    'Conformity',
    'Tradition',
    'Hedonism',
    'Benevolence',
]